# Generated by Django 4.0.4 on 2022-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='latitude',
            field=models.FloatField(default=56.8389261, max_length=160, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longitude',
            field=models.FloatField(default=60.6057025, max_length=160, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='places',
            name='url',
            field=models.SlugField(default='places', max_length=160),
        ),
    ]
